### ISSUE TITLE
Clarify release policy, distribution and tags

### ISSUE THREAD

**Issue by Blaisorblade** [borisveytsman/acmart#214]
I'm coorganizing Scala'17, a SIGPLAN-sponsored symposium colocated with SPLASH'17. CPC sent camera-ready instructions to our authors asking to use v1.46:

> The format of your paper must strictly adhere to the ACM Format (acmart v1.46 or newer).

Which I *think* isn't released, and I'm sure isn't the version available on http://www.acm.org/publications/proceedings-template or http://www.sigplan.org/Resources/Author/ (they both declare `2017/07/09 v1.43`).

It seems it would be good to clarify the release policy—I think it's "use whatever's distributed by ACM" but CPC seems to disagree.
Also, since there are further releases, and people do use them to incorporate later bugfixes, it could be useful to use git tags to mark the commit corresponding to actual releases. (GitHub also allows attaching compiled files, but that's not necessary). Right now, I'm convinced that v1.45 is complete while v1.46 is still evolving, but I wouldn't be surprised if other people were to guess differently, and I'm not 100% sure I understand correctly.

**Comment by Blaisorblade** [comment]
BTW, we're also contacting CPC to get clarifications on their side — this issue is about the acmart release policy.

**Comment by borisveytsman** [comment]
Hi, Paolo

Sorry for the delays: last minute bug fixes.  We released 1.46 half a hour ago.

**Comment by Blaisorblade** [comment]
Thanks a lot!

Just checked, http://www.acm.org/publications/proceedings-template now has the current HEAD.

@MatthewFluet, is that going to be propagated to http://www.sigplan.org/Resources/Author/ soon? Otherwise, I guess we'll have to send the compiled output to our authors soon.

**Comment by MatthewFluet** [comment]
@Blaisorblade O.k., the SIGPLAN packages have been updated.

**Comment by Blaisorblade** [comment]
Thanks a lot for the super-quick response! I'd still like to gently push for git tags, but that's not urgent 🙂.

**Comment by Blaisorblade** [comment]
@borisveytsman Sorry, but the main issue doesn't seem fixed — "what's 1.46" was a side question. I still don't see git tags, a release policy, or anything such.

**Comment by Blaisorblade** [comment]
Thanks a lot for the clarification!

**Comment by dbeyer** [comment]
Dear @borisveytsman,

I would like to second the suggestion by @Blaisorblade to use git tags (and keep them immutable).

The release page is currently empty:
https://github.com/borisveytsman/acmart/releases
That page could provide a nice overview over the releases and change logs.
Example (arbitrarily chosen): https://github.com/sosy-lab/benchexec/releases

Also, there is currently no reliable way to obtain a previous version.
Is release `1.46` the first commit with that number, or the last one?

Cheers,
Dirk

**Comment by borisveytsman** [comment]
THanks - will do
